[workspace]
members = [
    "rgpr_steamworks",
    "rgpr_steamworks_sys"
]
resolver = "2"

[workspace.package]
repository = "https://github.com/Cryotheus/rgpr_steamworks/"

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"
