[package]
name = "rgpr_steamworks_bindgen"
version = "0.1.0"
edition = "2024"
repository.workspace = true

[dependencies]
bindgen = "0.71.1"
prettyplease = { version = "0.2.31", features = ["verbatim"] }
thiserror = "2.0.12"
syn = "2.0.100"
